version: "3.9"
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - appNetwork

networks:
  appNetwork:

volumes:
  db:
    driver: local
  mongo_data:
    driver: local
